apiVersion: v1
kind: ReplicationController
metadata:
  name: demo48
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: demo48
  template:
    metadata:
      labels:
        app: demo48
    spec:
      serviceAccount: YOUR
      containers:
      - name: demo48
        image: ${docker-registry}/${docker-namespace}/demo48:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080